chore(package.json): bump angular.js to v1.9.2
xlts-dev/angularjs-material-vite pull request #18
Opened 2023-08-07 06:56 UTC by jzolnowski

Update to the latest version of angular.js v1.9.2

2023-08-07 10:17 UTC, gkalpak requested changes
We should also update the lockfile.

2023-08-11 08:20 UTC, gkalpak requested changes
This PR now contains more updates than just "angular.js to v1.9.2".
We should either limit the changes to AngularJS or update the commit message to reflect the actual changes.

2023-08-11 08:20 UTC, gkalpak commented on package-lock.json
> +  "lockfileVersion": 3,
We should not be updating the lockfile version in this commit.

2023-08-11 16:31 UTC, gkalpak requested changes
The changes lgtm, but I find the commit message confusing/unclear. What does _"angular.js-based libraries"_ refer to?

2023-08-14 13:00 UTC, jzolnowski commented
> The changes lgtm, but I find the commit message confusing/unclear. What does _"angular.js-based libraries"_ refer to?

angular.js-based librarie means all the rest bumped angularjs-based packages like:

```
"angular-animate": "npm:@xlts.dev/angular-animate@^1.9.2",
"angular-aria": "npm:@xlts.dev/angular-aria@^1.9.2",
"angular-material": "npm:@xlts.dev/angular-material@^1.2.4",
"angular-messages": "npm:@xlts.dev/angular-messages@^1.9.2"
```

2023-08-14 13:45 UTC, gkalpak requested changes
>> The changes lgtm, but I find the commit message confusing/unclear. What does _"angular.js-based libraries"_ refer to?
>
> angular.js-based librarie means all the rest bumped angularjs-based packages like:
>
> ```
> "angular-animate": "npm:@xlts.dev/angular-animate@^1.9.2",
> "angular-aria": "npm:@xlts.dev/angular-aria@^1.9.2",
> "angular-material": "npm:@xlts.dev/angular-material@^1.2.4",
> "angular-messages": "npm:@xlts.dev/angular-messages@^1.9.2"
> ```

I see. I don't think we need to explicitly mention these libraries in the commit message, since they are part of the AngularJS framework and can be collectively referred to as AngularJS. 

But this PR also updates other non-AngularJS related dependencies. We should either mention that in the commit message to move those other updates to a separate commit/PR.

2023-08-18 13:28 UTC, gkalpak requested changes
We should now update to v1.9.3 :wink:

2023-08-22 14:14 UTC, jzolnowski commented
> We should now update to v1.9.3 😉

Done

2023-08-22 17:59 UTC, gkalpak approved these changes

2023-08-22 18:00 UTC, merged